/**
 * KaizenIQ — Chat page ("Talk to the Agents")
 * ============================================
 * A conversational interface to the Master Orchestrator. Questions are
 * answered by the local Microsoft Foundry model, grounded in the FULL process
 * catalog (seeded + session-added) with process-id citations.
 *
 * Demonstrates live multi-step reasoning over organizational knowledge — the
 * highest-weighted judging criterion.
 */
import { useRef, useState, useEffect } from 'react';
import { sendChat } from '../api/client.js';

const SUGGESTIONS = [
  'Which processes are most critical and why?',
  'How many processes are drifting from documentation?',
  'What are the KPIs of the customer complaint process?',
  'Summarize the quality assurance processes.',
];

export default function Chat({ foundryMode }) {
  const [messages, setMessages] = useState([
    {
      role: 'agent',
      text: "Hi — I'm the KaizenIQ Master Orchestrator. Ask me anything about the "
        + "organization's ISO 9001 processes. I'm grounded in the full process "
        + "catalog and cite my sources.",
      citations: [],
    },
  ]);
  const [input, setInput] = useState('');
  const [busy, setBusy] = useState(false);
  const endRef = useRef(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, busy]);

  async function send(text) {
    const q = (text ?? input).trim();
    if (!q || busy) return;
    setInput('');
    setMessages((m) => [...m, { role: 'user', text: q }]);
    setBusy(true);
    try {
      const res = await sendChat(q);
      setMessages((m) => [
        ...m,
        { role: 'agent', text: res.answer, citations: res.citations || [], mode: res.mode },
      ]);
    } catch (e) {
      setMessages((m) => [
        ...m,
        { role: 'agent', text: `Sorry, something went wrong: ${e.message}`, citations: [] },
      ]);
    } finally {
      setBusy(false);
    }
  }

  return (
    <>
      <div className="page-head">
        <div className="eyebrow">Live reasoning</div>
        <h2>Talk to the Agents</h2>
        <p>
          Ask the Master Orchestrator about any process. Answers are generated by
          the {foundryMode === 'local' ? 'local Microsoft Foundry model' : 'knowledge base'},
          grounded in the full catalog with citations.
        </p>
      </div>

      <section className="ledger" style={{ display: 'flex', flexDirection: 'column', height: '62vh' }}>
        {/* Conversation */}
        <div style={{ flex: 1, overflowY: 'auto', padding: 18, display: 'flex', flexDirection: 'column', gap: 14 }}>
          {messages.map((m, i) => (
            <div key={i} style={{ alignSelf: m.role === 'user' ? 'flex-end' : 'flex-start', maxWidth: '80%' }}>
              <div style={{
                background: m.role === 'user' ? 'var(--ink)' : 'var(--paper)',
                color: m.role === 'user' ? 'var(--paper)' : 'var(--ink)',
                border: m.role === 'user' ? 'none' : '1px solid var(--line)',
                borderRadius: 10, padding: '10px 14px', fontSize: 13.5, lineHeight: 1.5,
                whiteSpace: 'pre-wrap',
              }}>
                {m.text}
              </div>
              {m.citations?.length > 0 && (
                <div style={{ marginTop: 5, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                  {m.citations.map((c) => (
                    <span key={c.id} className="badge tier" style={{ fontSize: 10.5 }}>
                      {c.id} · {c.title}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
          {busy && (
            <div style={{ alignSelf: 'flex-start', color: 'var(--stone)', fontSize: 13 }}>
              改 &nbsp;The orchestrator is thinking…
            </div>
          )}
          <div ref={endRef} />
        </div>

        {/* Suggestions (only before the first question) */}
        {messages.length === 1 && (
          <div style={{ padding: '0 18px 10px', display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            {SUGGESTIONS.map((s) => (
              <button key={s} className="btn ghost" style={{ fontSize: 12 }}
                onClick={() => send(s)} disabled={busy}>
                {s}
              </button>
            ))}
          </div>
        )}

        {/* Composer */}
        <div style={{ borderTop: '1px solid var(--line)', padding: 14, display: 'flex', gap: 8 }}>
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') send(); }}
            placeholder="Ask about any process…"
            disabled={busy}
            style={{
              flex: 1, padding: '10px 12px', border: '1px solid var(--line)',
              borderRadius: 'var(--radius)', fontFamily: 'var(--font-ui)', fontSize: 13.5,
              background: 'var(--surface)', color: 'var(--ink)',
            }}
          />
          <button className="btn" onClick={() => send()} disabled={busy || !input.trim()}>
            Send
          </button>
        </div>
      </section>
    </>
  );
}
