/**
 * KaizenIQ — Processes page
 * ==========================
 * The "visual catalyst": every documented ISO 9001 process rendered as a
 * Mermaid flowchart generated by the Flowchart Agent, side by side with the
 * process facts (owner, clause, KPIs, document age).
 *
 * Mermaid rendering notes:
 *   - mermaid v11 API: initialize once, then `mermaid.render(id, code)`
 *   - each render uses a unique element id to avoid stale-SVG collisions
 *   - failures are caught so a bad diagram can never break the page
 */
import { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
import { getFlowchart } from '../api/client.js';

// One-time engine setup; 'neutral' theme matches the paper palette.
mermaid.initialize({
  startOnLoad: false,
  theme: 'neutral',
  flowchart: { curve: 'basis' },
  fontFamily: 'Zen Kaku Gothic New, sans-serif',
});

let renderSeq = 0; // unique id counter for mermaid.render

export default function Processes({ data }) {
  // Process ids come from the flowcharts map; rich details are fetched once
  // from /api/processes by useProcessIndex below.
  const list = data.flowcharts ? Object.keys(data.flowcharts.flowcharts) : [];
  const allProcesses = useProcessIndex(data);

  const [selected, setSelected] = useState(list[0] || 'PROC-001');
  const [svg, setSvg] = useState('');
  const [error, setError] = useState(null);
  const boxRef = useRef(null);

  // Render the Mermaid chart whenever the selection changes.
  useEffect(() => {
    let cancelled = false;
    async function render() {
      setError(null);
      setSvg('');
      try {
        const { mermaid: code } = await getFlowchart(selected);
        const id = `kaizen-flow-${++renderSeq}`;
        const { svg } = await mermaid.render(id, code);
        if (!cancelled) setSvg(svg);
      } catch (e) {
        if (!cancelled) setError(e.message);
      }
    }
    render();
    return () => { cancelled = true; };
  }, [selected]);

  const proc = allProcesses[selected];

  return (
    <>
      <div className="page-head">
        <div className="eyebrow">Visual catalyst</div>
        <h2>Process Flowcharts</h2>
        <p>
          Every documented process, automatically rendered by the Flowchart Agent.
          Decision-type steps appear as diamonds; the KPI node summarizes current
          performance against target.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: 22, alignItems: 'start' }}>
        {/* ---- Process selector ------------------------------------- */}
        <section className="ledger">
          <header><h3>ISO 9001 processes</h3></header>
          <div className="proc-list">
            {Object.values(allProcesses).map((p) => (
              <button
                key={p.id}
                className={`proc-row ${selected === p.id ? 'active' : ''}`}
                onClick={() => setSelected(p.id)}
              >
                <span className="mono">{p.id}</span>
                <span>{p.name}</span>
                <small>v{p.document_version}</small>
              </button>
            ))}
          </div>
        </section>

        {/* ---- Flowchart + facts ------------------------------------ */}
        <div>
          {proc && (
            <section className="ledger">
              <header>
                <h3>{proc.name}</h3>
                <span className="sub">{proc.iso_clause}</span>
              </header>
              <div className="body" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 14, fontSize: 12.5 }}>
                <div><strong>Owner</strong><br /><span style={{ color: 'var(--stone)' }}>{proc.owner}</span></div>
                <div><strong>Team</strong><br /><span style={{ color: 'var(--stone)' }}>{proc.responsible_team}</span></div>
                <div><strong>Criticality</strong><br />
                  <span className={`badge ${proc.criticality === 'HIGH' ? 'high' : 'medium'}`}>{proc.criticality}</span>
                </div>
                <div><strong>Last updated</strong><br /><span className="mono" style={{ color: 'var(--stone)' }}>{proc.last_updated}</span></div>
              </div>
            </section>
          )}

          <div className="flowchart-box" ref={boxRef}>
            {error && <p style={{ color: 'var(--hanko)' }}>Could not render flowchart: {error}</p>}
            {!svg && !error && <p style={{ color: 'var(--stone)' }}>Rendering…</p>}
            {/* SVG comes from our own backend-generated Mermaid source */}
            {svg && <div dangerouslySetInnerHTML={{ __html: svg }} />}
          </div>
        </div>
      </div>
    </>
  );
}

/**
 * Build an id → process map from whatever the analysis payload provides.
 * Falls back to fetching nothing extra: the payload already includes the
 * organization process list through current_state evidence; here we only
 * need id, name, owner, clause — provided via data.processes when present.
 */
function useProcessIndex(data) {
  const [index, setIndex] = useState({});
  useEffect(() => {
    // The /api/processes payload is the richest source; fetch once.
    fetch('/api/processes')
      .then((r) => r.json())
      .then(({ processes }) => {
        const map = {};
        for (const p of processes) map[p.id] = p;
        setIndex(map);
      })
      .catch(() => {
        // Fallback: minimal index from the analysis assessments.
        const map = {};
        for (const a of data.current_state.assessments) {
          map[a.process_id] = { id: a.process_id, name: a.process_name, document_version: '—' };
        }
        setIndex(map);
      });
  }, [data]);
  return index;
}
